### PR TITLE
Fix saving unsaved data in finish workflow action #10157

### LINKED ISSUE #10157: [workflows] this.finishWorkflow is not a function
Advance to a workflow step that allows you to have unsaved data and a Save and Complete Workflow action, such as: AfS X/Y Upload Workflow > File Interpretation step.

Click Save and Complete Workflow.

Result:
```js
Uncaught (in promise) TypeError: this.finishWorkflow is not a function
```

Regression in 7cccf96d2d755fda5f3fc9172c5586bee5351442 (unreleased)

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
https://github.com/archesproject/arches/commit/7cccf96d2d755fda5f3fc9172c5586bee5351442 relied on a recursive call to `self.finishWorkflow()` to handle marking the workflow as complete, but besides the `TypeError` from using `this` instead of `self`, it was also executing a bunch of unnecessary requests instead of only sending one POST for the unsaved data and one POST for marking complete. Extracted a new function to mitigate that.

### Issues Solved
Closes #10157

### CODE REVIEW

File: arches/app/media/js/viewmodels/workflow.js [hunk 1]
```diff
@@ -440,6 +434,16 @@ define([
             });
 
             window.location.assign(self.quitUrl);
+        }
+
+        this.finishWorkflow = function() {
+            if (self.activeStep().hasUnsavedData()) {
+                self.activeStep().save().then(function() {
+                    self.markWorkflowComplete();
+                });
```
Comment (chrabyrd) [inline arches/app/media/js/viewmodels/workflow.js:443]: nit: this can be reduced to `self.activeStep().save().then(self.markWorkflowComplete)`

File: arches/app/media/js/viewmodels/workflow.js [hunk 2]
```diff
@@ -440,6 +434,16 @@ define([
...
+                return;
+            }
+            self.markWorkflowComplete();
```
Comment (chrabyrd) [inline arches/app/media/js/viewmodels/workflow.js:446]: nit ( since we're refactoring ): replacing the `return` statement with `if/else` logic is slightly more readable.

**Review by chrabyrd — CHANGES_REQUESTED** [review]
overall looks good, just a few nits about stuff that was already there since we're refactoring.

**Review by chrabyrd — APPROVED** [review]
lgtm!
