### ISSUE TITLE
ExternalOauth.callback view raising exception after v8 upgrade

### ISSUE THREAD

**Issue by bferguso** [archesproject/arches#12121]
When upgrading a 7.6 project using External Oauth to 8.0 we are now getting the following exception:
```
bcap7-6  | TypeError: ExternalOauth.callback() missing 1 required positional argument: 'request'
bcap7-6  | Internal Server Error: /bcap/auth/eoauth_cb
bcap7-6  | Traceback (most recent call last):
bcap7-6  |   File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
bcap7-6  |     response = get_response(request)
bcap7-6  |                ^^^^^^^^^^^^^^^^^^^^^
bcap7-6  |   File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/base.py", line 197, in _get_response
bcap7-6  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
bcap7-6  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bcap7-6  |   File "/usr/local/lib/python3.11/dist-packages/django/utils/decorators.py", line 48, in _wrapper
bcap7-6  |     return bound_method(*args, **kwargs)
bcap7-6  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bcap7-6  | TypeError: ExternalOauth.callback() missing 1 required positional argument: 'request'
```

The same codebase continues to work with Arches 7.6, and changing our implementation of `ExternalOauth.callback` to point back to the same method in Arches Core we continue to get the same exception.

**Comment by bferguso** [comment]
Currently looking into issue, but thought I'd log this in case someone else runs into this.

**Comment by jacobtylerwalls** [comment]
Debugged with @bferguso a bit yesterday: Django 5.2 no longer masks the user error of calling `@method_decorator` on a pure function (i.e. function not taking self).

We can fix this easily in Arches, and we may as well target 7.6

**Comment by bferguso** [comment]
Also working through a fix for 8.0 as it seems there are some deeper issues with the ExternalOauth sequencing. Might be worth pushing the same fix through 7.6 & 8.0 if possible.

**Comment by jacobtylerwalls** [comment]
If you don't mind I'll send you a smaller PR for the method_decorator change, should be reviewable separately?
