### PR TITLE
Remove @method_decorator from ExternalOauth.callback #12121

### LINKED ISSUE #12121: ExternalOauth.callback view raising exception after v8 upgrade
When upgrading a 7.6 project using External Oauth to 8.0 we are now getting the following exception:
```
bcap7-6  | TypeError: ExternalOauth.callback() missing 1 required positional argument: 'request'
bcap7-6  | Internal Server Error: /bcap/auth/eoauth_cb
bcap7-6  | Traceback (most recent call last):
bcap7-6  |   File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
bcap7-6  |     response = get_response(request)
bcap7-6  |                ^^^^^^^^^^^^^^^^^^^^^
bcap7-6  |   File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/base.py", line 197, in _get_response
bcap7-6  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
bcap7-6  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bcap7-6  |   File "/usr/local/lib/python3.11/dist-packages/django/utils/decorators.py", line 48, in _wrapper
bcap7-6  |     return bound_method(*args, **kwargs)
bcap7-6  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bcap7-6  | TypeError: ExternalOauth.callback() missing 1 required positional argument: 'request'
```

The same codebase continues to work with Arches 7.6, and changing our implementation of `ExternalOauth.callback` to point back to the same method in Arches Core we continue to get the same exception.

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
This method was incorrectly decorated. By grace this was working on Django 4.2, but on 5.x it's no longer lenient.

### Issues Solved

Closes #12121

### Checklist

-   I targeted one of these branches:
    - [ ] dev/8.1.x (under development): features, bugfixes not covered below
    - [ ] dev/8.0.x (main support): regressions, crashing bugs, security issues, major bugs in new features
    - [x] dev/7.6.x (extended support): major security issues, data loss issues
-   [x] I added a changelog in arches/releases
-   [ ] I submitted a PR to arches-docs (if appropriate)
-   [ ] Unit tests pass locally with my changes
-   [ ] I added tests that prove my fix is effective or that my feature works
-   [ ] My test fails on the target branch

#### Ticket Background
*   Found by: @bferguso

### Further comments
A more invasive change would have been to make these class-based views actually class-based with methods instead of pure functions. But we defer that to another day.

### CODE REVIEW

**Review by bferguso — APPROVED** [review]
Looks good! This fixed using Django 5.2 in Arches 7.6 instance.
