### ISSUE TITLE
[workflows] this.finishWorkflow is not a function

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#10157]
Advance to a workflow step that allows you to have unsaved data and a Save and Complete Workflow action, such as: AfS X/Y Upload Workflow > File Interpretation step.

Click Save and Complete Workflow.

Result:
```js
Uncaught (in promise) TypeError: this.finishWorkflow is not a function
```

Regression in 7cccf96d2d755fda5f3fc9172c5586bee5351442 (unreleased)

**Comment by chrabyrd** [comment]
resolved in #10158
